### ISSUE TITLE
swportal sprint 20-1

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#1]
# swportal sprint 20-1

Sciwork Portal (swportal) is the future website planned to serve at http://sciwork.dev/, to replace the current "sciwork 2020 conference" web site.  The source files are hosted in https://github.com/sciwork/swportal/ (this repository), and this sprint is to kick off the development.

* Date: 11th July 2020
* Time: 14:00 -- 17:00
* Location: Rm203 2F, Science Building 2, NCTU
* Registration page: https://sciwork.kktix.cc/events/scisprint20jul
* Discord: https://discord.gg/6MAkFrD
* Telegram: https://t.me/scisprint20jul

Topics included in the sprint:

* How does the website works?
* DNS System
  * `.dev` domain
  * HTTP v.s. HTTPs
* Web Server
  * [Netlify](https://www.netlify.com)
* Static Website Generator
  * Tailwind CSS
  * Pelican

Note: https://us02web.zoom.us/j/83281512748?pwd=QTFxMzd1bnUvMTdQcmZCVm9heUU1dz09

This issue is to track the related information, and will be continuously updated.

(Last updated on 11th July 2020.)

**Comment by josix** [comment]
Hello @yungyuc, thank you for holding this sprint. I am wondering if this sprint could be joined remotely because I have difficulty going to Hsinchu?

**Comment by yungyuc** [comment]
Hi @josix, I think the volunteering resources are only available to do it either online or in person, not both.  For this time, we are planning for an in-person event, and it could be a bit challenging for us to arrange online participation.

We very much appreciate your interests in participation, and understand that Hsinchu is not the most accessible place for everyone.  For swportal project pre we, perhaps we can collaborate right on GitHub to compensate the inaccessibility.  We could also try to plan for a future event that is more accessible to you.  Please let us know how do you think.

**Comment by josix** [comment]
I got it! Thank you for your reply. I guess it would be great that team members can focus on preparing the sprint. And I can track the progress on GitHub after the sprint is held. I think GitHub is pretty convenient to collaborate with you and I will keep follow up on this project to see if there is anything I can help.

**Comment by yungyuc** [comment]
Push back the date to be in July.

**Comment by tenacity0310** [comment]
in!

**Comment by yungyuc** [comment]
Thank you all for joining the sprint.  The website is going online: https://sciwork.dev/.  We will keep developing it and host subsequent sprints!
