### ISSUE TITLE
Add new navbar tab for meetup

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#129]
The sciwork community is planning for a new type of event named "meetup" (see discussions in https://discord.gg/wtEkBQfBtg), and there should be a navbar tab and a list page for it, just like those of "sprint".

The "meetup" tab can be at the left or right of the "sprint" tab.

**Comment by cstnaya** [comment]
#There are 2 things to do.  One is adding new item "meetup" in menu, and the other one is creating new page for meetup.

1. create new tab **meetup** in menu
    - at line 21 in `pelicanconf.py`,  add `('meetup', 'meetup'),`

```
MENUITEMS = (
    ('home', ''),
    #('Blog', 'blog'),
    ('sprint', 'sprint'), 
    ('meetup', 'meetup'), # <------ add the line here
    ('about', 'about'),    
)
```

2. create new page "**meetup**"

    - in content/pages, create new file: `meetup/index.rst`

and the directory will now look like this:
```
content
    └─ pages
         └─ meetup
             └─ index.rst
...
``` 

Inside the `meetup/index.rst`, add thest text:
```
======
meetup
======

:date: 2022-09-08
:url:
:save_as: meetup/index.html


```

I'll create a PR later. ('ω')ノ

**Comment by yungyuc** [comment]
Thanks @cstnaya .  I assign the issue to you to help you keep track of it.
