### ISSUE TITLE
Add the web page for October sprint

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#134]
@YenPeiChen07 , could you please help create a web page under https://sciwork.dev/meetup/ for the October sprint?

The format can reference the career panel in May: https://sciwork.dev/sprint/2022/05-nycu-career , and the contents can be taken from the workbook: https://hackmd.io/@sciwork/meetup-2210 .  If there are any questions we can discuss here or in the [channel](https://discord.gg/wtEkBQfBtg).

**Comment by YenPeiChen07** [comment]
Sure, I could help with this.

**Comment by yungyuc** [comment]
@YenPeiChen07 It's one month before the event.  It would be good to have the web page set up around this week.

**Comment by yungyuc** [comment]
Thanks for the addition at https://sciwork.dev/meetup/2022/10-nycu , @YenPeiChen07 .

Reading the page I just realize that the event date is in a very low location.

**Comment by yungyuc** [comment]
Thanks a lot, @YenPeiChen07
