### ISSUE TITLE
Plan for 2023 March scisprint

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#164]
We will be starting to plan for the March scisprint.  Workbook is at https://hackmd.io/@sciwork/scisprint-2303 .  This issue is created to keep track of all related checkins.

**Comment by yungyuc** [comment]
@YenPeiChen07 Could you please help or ask someone to create a sprint page?

**Comment by YenPeiChen07** [comment]
> @YenPeiChen07 Could you please help or ask someone to create a sprint page?

Sure. I will find someone to help with this.

**Comment by yungyuc** [comment]
Thanks @YenPeiChen07 .  Hopefully it can be published in a couple of days.  I have confirmed with NTHU for the venue.
