### ISSUE TITLE
Update 23 feb sprint page with the after-event contents

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#165]
We had a successful February sprint and created an album https://www.flickr.com/photos/sciwork/albums/72177720305939446 and a blog https://medium.com/sciwork/scisprint-2023-february-in-taipei-e565f2d19b1a for it.  The after-event contents are also great work and should be added to the event page https://sciwork.dev/sprint/2023/02-taipei .

**Comment by yungyuc** [comment]
@YenPeiChen07 and/or @cstnaya would you have time to take a look at it?

**Comment by YenPeiChen07** [comment]
> @YenPeiChen07 and/or @cstnaya would you have time to take a look at it?

Yes. It is a great idea so that people will know more about the sprint and we have done in the event.

I could take a look with this or just add sections for the album and blog in the event page. We could also discuss about how to make it more visible.

**Comment by yungyuc** [comment]
Thanks @YenPeiChen07 , let me assign this ticket to you.  By visibility do you mean visual design / typesetting?

**Comment by cstnaya** [comment]
Should we use `iframe` or just add a link?
It looks like it is possible to embed flickr album in website.  [Read detail here](https://www.flickrhelp.com/hc/en-us/articles/4404078014356-Share-or-embed-Flickr-photos-albums).

I guess using `iframe` to embed the album, and adding the link to medium blog might be a good choice.

**Comment by yungyuc** [comment]
Embedding flickr in the sprint page sounds like a great idea.  +1 from me.

**Comment by YenPeiChen07** [comment]
Embedding flickr in the sprint page also looks good for me.

The visibility I mentioned before means that how to let people check them out easily. My idea is to create the sections in navigation bar (like album or blog). It's just a random idea, we could discuss more in the future.

**Comment by yungyuc** [comment]
@YenPeiChen07 sounds good.  At the moment we can focus on the concrete ideas and rolling them out.  New things can be done in later phases.
