### ISSUE TITLE
Repurpose meetup section for weekly meetings

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#167]
In the past we use the name ["meetup"](https://sciwork.dev/meetup/) for irregular meetings like https://sciwork.dev/meetup/2022/10-nycu .  Recently the community wanted to organize a series of weekly meetings and found meetup is a suitable name.

This issue is filed to track repurposing the name meetup for the weekly meeting series.  We should change the website accordingly.  The past "meetup" event should be moved to the ["sprint"](https://sciwork.dev/sprint/) list.  And the meetup list should host information for the new weekly series.

**Comment by cstnaya** [comment]
Ok, I will create a new PR for this!
