### ISSUE TITLE
Sub-optimal preview in facebook messenger

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#17]
There doesn't seem to be correct preview when the link is in FB messenger.  I didn't check that in other IM/social media, though.

![image](https://user-images.githubusercontent.com/399122/87373039-7aeb0400-c5bb-11ea-8149-4abb01ea0414.jpeg)

**Comment by chestercheng** [comment]
The `SITEURL` environment variable did not set in Netlify build setting, sometimes the rich preview image cannot be loaded successfully...
