### ISSUE TITLE
Sprint page for May

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#179]
Create the sciwork.dev webpage for scisprint Hsinchu in May

**Comment by YenPeiChen07** [comment]
@yungyuc I would like to double check the venue for May sprint. Will we still use the CTC in NTHU?

**Comment by yungyuc** [comment]
> @yungyuc I would like to double check the venue for May sprint. Will we still use the CTC in NTHU?

Thanks for the reminder.  We have not confirmed with CTC.  I just sent them an email and copied you.  Let's wait for the confirmation.

**Comment by YenPeiChen07** [comment]
> @YenPeiChen07 It's confirmed.

Thanks for your help. 

@linoil Could you please update the information about venue. We will use CTC in May sprint, which is the same as the April one.

**Comment by YenPeiChen07** [comment]
The kktix page for May sprint is published. @linoil Could you please also update the link for registration?

The link for the kktix page: https://sciwork.kktix.cc/events/scisprint-202305-hsinchu

**Comment by YenPeiChen07** [comment]
Solved by #202
