### ISSUE TITLE
swportal sprint 20-2

### ISSUE THREAD

**Issue by chestercheng** [sciwork/swportal#18]
# swportal sprint 20-2

Sciwork Portal (swportal) is the future website planned to serve at http://sciwork.dev/, to replace the current "sciwork 2020 conference" web site. The source files are hosted in https://github.com/sciwork/swportal/ (this repository), and this sprint is to kick off the development.

- Date: 1 August 2020
- Time: 14:00 -- 17:00
- Location: Rm203 2F, Science Building 2, NCTU
- Registration page: https://sciwork.kktix.cc/events/swportal20-2
- Discord: https://discord.gg/6MAkFrD

Last sprint: #1 

Topics included in the sprint:

- Familiar with the command line operations
- Static website generator (Pelican)

This issue is to track the related information, and will be continuously updated.

(Last updated on 27th July 2020.)

**Comment by yungyuc** [comment]
Close the finished sprint.
