### ISSUE TITLE
Issue with sending email through Gmail SMTP in pretalx and swportal integration

### ISSUE THREAD

**Issue by chestercheng** [sciwork/swportal#205]
I am planning to integrate [pretalx](https://github.com/pretalx/pretalx) into swportalfor our event management needs.
However, I have noticed an issue with sending emails through Gmail SMTP as described in the [pretalx FAQ](https://docs.pretalx.org/faq.html).

The root cause for this issue is that [Google has decided to phase out support for Less Secure Apps](https://support.google.com/accounts/answer/6010255), and Gmail SMTP relies on this mechanism for sending emails.

A possible solution is to switch the mail backend to the  [Gmail API](https://developers.google.com/gmail/api/guides/sending).

**Comment by yungyuc** [comment]
Thanks, @chestercheng .  We will use this issue to track and drive the further development of the sciwork websites.

**Comment by cstnaya** [comment]
@chestercheng How about using the 3rd party mail service, like [SendGrid](https://sendgrid.com/).
Or some other 3rd party services, you can read [this](https://medium.com/@Negaihoshi/%E7%AC%AC%E4%B8%89%E6%96%B9%E5%AF%84%E4%BF%A1%E6%9C%8D%E5%8B%99%E5%88%86%E6%9E%90-2ddd72009705).

I hope it helps a lot!

**Comment by yungyuc** [comment]
@chestercheng is this issue still there?

**Comment by chestercheng** [comment]
No, this issue has been fixed. I have changed the Pretalx email backend to Gmail API.
I will now close this issue.
