### ISSUE TITLE
Correct the title of the CFD workshop

### ISSUE THREAD

**Issue by yungyuc** [sciwork/swportal#369]
@j8xixo12 and @kuomc , could you please correct the title of the CFD workshop to be "advance CFD software development"?  It's written in the workbook.  Both portal https://sciwork.dev/workshop/2024/03-workshop and kktix https://sciwork.kktix.cc/events/cfdworkshop-2024-march should be corrected.

<img width="657" alt="image" src="https://github.com/sciwork/swportal/assets/399122/e923f691-08dd-4705-ba41-5ca4bc2a1fab">

**Comment by yungyuc** [comment]
Could you please also add the title in the section of [About the workshop](https://sciwork.dev/workshop/2024/03-workshop#about-the-workshop)?

<img width="1098" alt="image" src="https://github.com/sciwork/swportal/assets/399122/22a1f546-24b1-4b53-a03d-07190394ded5">

**Comment by kuomc** [comment]
Close #370

**Comment by kuomc** [comment]
close this issue because the #370 is merged.
