### ISSUE TITLE
[meetup] add 1016 agenda 

### ISSUE THREAD

**Issue by ThreeMonth03** [sciwork/swportal#478]
Few days ago, @yungyuc mentioned that we could add the nsd project presentation in our meetup agenda. @jteng2127 @ntut-xuan Could you please make a pull request before next Wednesday?

**Comment by yungyuc** [comment]
@ThreeMonth03, could you please create the meetup page first?  In the PR, you may loop in @jteng2127 and @ntut-xuan to show them where to add the project discussion information.

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03, could you please create the meetup page first? In the PR, you may loop in @jteng2127 and @ntut-xuan to show them where to add the project discussion information.

No problem.

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03, could you please create the meetup page first? In the PR, you may loop in @jteng2127 and @ntut-xuan to show them where to add the project discussion information.

In pr #479 , I create the meetup page.

**Comment by ThreeMonth03** [comment]
> > @ThreeMonth03, could you please create the meetup page first? In the PR, you may loop in @jteng2127 and @ntut-xuan to show them where to add the project discussion information.
> 
> In pr #479 , I create the meetup page.

The pr #479 is merged.  @jteng2127 @ntut-xuan Could you please make a pull request to enhance the agenda in [content/pages/meetup/2024/1016-nycu.rst](https://github.com/sciwork/swportal/blob/develop/content/pages/meetup/2024/1016-nycu.rst) ?

**Comment by ThreeMonth03** [comment]
close #478
