### ISSUE TITLE
[sprint] Update project list and registration link for November Hsinchu sprint

### ISSUE THREAD

**Issue by YenPeiChen07** [sciwork/swportal#486]
The November sprint in Hsinchu is scheduled on November, 2nd. 

The [webpage](https://sciwork.dev/sprint/2024/11-hsinchu) is ready but the project list and registration link has not been confirmed. We might need to update them soon.

**Comment by YenPeiChen07** [comment]
@meng5113, do you have time to it?

**Comment by meng5113** [comment]
> @meng5113, do you have time to it?

No problem, I'll do it this weekend.

**Comment by YenPeiChen07** [comment]
> > @meng5113, do you have time to it?
> 
> No problem, I'll do it this weekend.

Thank you, @meng5113.

**Comment by YenPeiChen07** [comment]
This issue has been solved by #489.
